In [1]:
import pandas as pd
import numpy as np
import random
import sklearn.datasets as datasets
from data_consistency_checker import DataConsistencyChecker

In [2]:
pd.options.display.max_columns = 1000
pd.options.display.max_colwidth = 1000
pd.options.display.max_rows = 1000
pd.options.display.width = 10000

In [3]:
data = datasets.load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)
df.head()

   mean radius  mean texture  mean perimeter  mean area  mean smoothness  mean compactness  mean concavity  mean concave points  mean symmetry  mean fractal dimension  radius error  texture error  perimeter error  area error  smoothness error  compactness error  concavity error  concave points error  symmetry error  fractal dimension error  worst radius  worst texture  worst perimeter  worst area  worst smoothness  worst compactness  worst concavity  worst concave points  worst symmetry  worst fractal dimension
0        17.99         10.38          122.80     1001.0          0.11840           0.27760          0.3001              0.14710         0.2419                 0.07871        1.0950         0.9053            8.589      153.40          0.006399            0.04904          0.05373               0.01587         0.03003                 0.006193         25.38          17.33           184.60      2019.0            0.1622             0.6656           0.7119                0.2654          0.4601                  0.11890
1        20.57         17.77          132.90     1326.0          0.08474           0.07864          0.0869              0.07017         0.1812                 0.05667        0.5435         0.7339            3.398       74.08          0.005225            0.01308          0.01860               0.01340         0.01389                 0.003532         24.99          23.41           158.80      1956.0            0.1238             0.1866           0.2416                0.1860          0.2750                  0.08902
2        19.69         21.25          130.00     1203.0          0.10960           0.15990          0.1974              0.12790         0.2069                 0.05999        0.7456         0.7869            4.585       94.03          0.006150            0.04006          0.03832               0.02058         0.02250                 0.004571         23.57          25.53           152.50      1709.0            0.1444             0.4245           0.4504                0.2430          0.3613                  0.08758
3        11.42         20.38           77.58      386.1          0.14250           0.28390          0.2414              0.10520         0.2597                 0.09744        0.4956         1.1560            3.445       27.23          0.009110            0.07458          0.05661               0.01867         0.05963                 0.009208         14.91          26.50            98.87       567.7            0.2098             0.8663           0.6869                0.2575          0.6638                  0.17300
4        20.29         14.34          135.10     1297.0          0.10030           0.13280          0.1980              0.10430         0.1809                 0.05883        0.7572         0.7813            5.438       94.44          0.011490            0.02461          0.05688               0.01885         0.01756                 0.005115         22.54          16.67           152.20      1575.0            0.1374             0.2050           0.4000                0.1625          0.2364                  0.07678

In [4]:
dc = DataConsistencyChecker() 
dc.init_data(df)

## Run the SIMILAR_WRT_RATIO test

In [5]:
# Run a small set of tests to start. In this example, we run a single test.

_ = dc.check_data_quality(execute_list=['SIMILAR_WRT_RATIO'])

Executing test  33: SIMILAR_WRT_RATIO

Data consistency check complete.
Analysed 569 rows, 30 columns
Executed 1 tests.

Patterns without Exceptions:
Found 3 patterns without exceptions
1 tests (100.00% of tests) identified at least one pattern without exceptions each.
By default some patterns are not listed in calls to display_detailed_results().

Patterns with Exceptions:
Found 3 patterns with exceptions
1 tests (100.00% of tests) flagged at least one exception each.
Flagged 5 row(s) with at least one exception.
Flagged 5 column(s) with at least one exception.

In [6]:
# In the next few cells, we look at the output of the tests. 

dc.summarize_patterns_and_exceptions()

             Test ID  Number Patterns without Exceptions  Number Patterns with Exceptions
0  SIMILAR_WRT_RATIO                                   3                                3

In [7]:
dc.get_patterns_list()

             Test ID                                 Column(s)                                                                                   Description of Pattern  Pattern ID
0  SIMILAR_WRT_RATIO          "mean radius" AND "worst radius"  "mean radius" and "worst radius" have consistently similar values in terms of their ratio (with 0 ro...           0
1  SIMILAR_WRT_RATIO    "mean perimeter" AND "worst perimeter"  "mean perimeter" and "worst perimeter" have consistently similar values in terms of their ratio (wit...           1
2  SIMILAR_WRT_RATIO  "mean smoothness" AND "worst smoothness"  "mean smoothness" and "worst smoothness" have consistently similar values in terms of their ratio (w...           2

In [8]:
dc.get_exceptions_list()

             Test ID                                               Column(s)                                                                                   Description of Pattern  Number of Exceptions  Issue ID
0  SIMILAR_WRT_RATIO                      "mean texture" AND "worst texture"  "mean texture" and "worst texture" have consistently similar values in terms of their ratio (with 0 ...                     1         0
1  SIMILAR_WRT_RATIO         "mean smoothness" AND "worst fractal dimension"  "mean smoothness" and "worst fractal dimension" have consistently similar values in terms of their r...                     2         1
2  SIMILAR_WRT_RATIO  "mean fractal dimension" AND "worst fractal dimension"  "mean fractal dimension" and "worst fractal dimension" have consistently similar values in terms of ...                     2         2

## Run the CORRELATED_NUMERIC test

In [9]:
# Here we run a second test on the same dataset. 

_ = dc.check_data_quality(execute_list=['CORRELATED_NUMERIC'])

Executing test  43: CORRELATED_NUMERIC

Data consistency check complete.
Analysed 569 rows, 30 columns
Executed 1 tests.

Patterns without Exceptions:
Found 4 patterns without exceptions
1 tests (100.00% of tests) identified at least one pattern without exceptions each.
By default some patterns are not listed in calls to display_detailed_results().

Patterns with Exceptions:
Found 0 patterns with exceptions
0 tests (0.00% of tests) flagged at least one exception each.
Flagged 0 row(s) with at least one exception.
Flagged 0 column(s) with at least one exception.

In [10]:
# By default, calling check_data_quality() again will start fresh, which
# is useful where you have a new set of tests you wish to execute. We
# see in the next few cells that the CORRELATED_NUMERIC test found four
# patterns and no exceptions. These are shown, but the results of
# SIMILAR_WRT_RATIO are removed. 

dc.summarize_patterns_and_exceptions()

              Test ID  Number Patterns without Exceptions Number Patterns with Exceptions
0  CORRELATED_NUMERIC                                   4

In [11]:
dc.get_patterns_list()

              Test ID                           Column(s)                                                                                   Description of Pattern  Pattern ID
0  CORRELATED_NUMERIC  "mean radius" AND "mean perimeter"  "mean radius" is consistently similar (with 0.0% identical values), with respect to rank, to "mean p...           0
1  CORRELATED_NUMERIC       "mean radius" AND "mean area"  "mean radius" is consistently similar (with 0.0% identical values), with respect to rank, to "mean a...           1
2  CORRELATED_NUMERIC    "mean perimeter" AND "mean area"  "mean perimeter" is consistently similar (with 0.0% identical values), with respect to rank, to "mea...           2
3  CORRELATED_NUMERIC     "worst radius" AND "worst area"  "worst radius" is consistently similar (with 0.0% identical values), with respect to rank, to "worst...           3

In [12]:
dc.get_exceptions_list()

## Run both tests again

In [13]:
# We repeat the above example, this time combining the results of all tests.

_ = dc.check_data_quality(execute_list=['SIMILAR_WRT_RATIO'])

Executing test  33: SIMILAR_WRT_RATIO

Data consistency check complete.
Analysed 569 rows, 30 columns
Executed 1 tests.

Patterns without Exceptions:
Found 3 patterns without exceptions
1 tests (100.00% of tests) identified at least one pattern without exceptions each.
By default some patterns are not listed in calls to display_detailed_results().

Patterns with Exceptions:
Found 3 patterns with exceptions
1 tests (100.00% of tests) flagged at least one exception each.
Flagged 5 row(s) with at least one exception.
Flagged 5 column(s) with at least one exception.

In [14]:
dc.summarize_patterns_and_exceptions()

             Test ID  Number Patterns without Exceptions  Number Patterns with Exceptions
0  SIMILAR_WRT_RATIO                                   3                                3

In [15]:
# Here we set append_results to True, which saves the previous findings, and 
# appends any results from the current set of tests. 

_ = dc.check_data_quality(execute_list=['CORRELATED_NUMERIC'], append_results=True)

Executing test  43: CORRELATED_NUMERIC

Data consistency check complete.
Analysed 569 rows, 30 columns
Executed 2 tests.

Patterns without Exceptions:
Found 7 patterns without exceptions
2 tests (100.00% of tests) identified at least one pattern without exceptions each.
By default some patterns are not listed in calls to display_detailed_results().

Patterns with Exceptions:
Found 3 patterns with exceptions
1 tests (50.00% of tests) flagged at least one exception each.
Flagged 5 row(s) with at least one exception.
Flagged 5 column(s) with at least one exception.

In [16]:
dc.summarize_patterns_and_exceptions()

              Test ID  Number Patterns without Exceptions Number Patterns with Exceptions
0   SIMILAR_WRT_RATIO                                   3                               3
1  CORRELATED_NUMERIC                                   4

In [17]:
dc.get_patterns_list()

              Test ID                                 Column(s)                                                                                   Description of Pattern  Pattern ID
0   SIMILAR_WRT_RATIO          "mean radius" AND "worst radius"  "mean radius" and "worst radius" have consistently similar values in terms of their ratio (with 0 ro...           0
1   SIMILAR_WRT_RATIO    "mean perimeter" AND "worst perimeter"  "mean perimeter" and "worst perimeter" have consistently similar values in terms of their ratio (wit...           1
2   SIMILAR_WRT_RATIO  "mean smoothness" AND "worst smoothness"  "mean smoothness" and "worst smoothness" have consistently similar values in terms of their ratio (w...           2
3  CORRELATED_NUMERIC        "mean radius" AND "mean perimeter"  "mean radius" is consistently similar (with 0.0% identical values), with respect to rank, to "mean p...           3
4  CORRELATED_NUMERIC             "mean radius" AND "mean area"  "mean radius" is consistently similar (with 0.0% identical values), with respect to rank, to "mean a...           4
5  CORRELATED_NUMERIC          "mean perimeter" AND "mean area"  "mean perimeter" is consistently similar (with 0.0% identical values), with respect to rank, to "mea...           5
6  CORRELATED_NUMERIC           "worst radius" AND "worst area"  "worst radius" is consistently similar (with 0.0% identical values), with respect to rank, to "worst...           6